// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: models.proto

package models

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SSH service

func NewSSHEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SSH service

type SSHService interface {
	Echo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type sSHService struct {
	c    client.Client
	name string
}

func NewSSHService(name string, c client.Client) SSHService {
	return &sSHService{
		c:    c,
		name: name,
	}
}

func (c *sSHService) Echo(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "SSH.Echo", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SSH service

type SSHHandler interface {
	Echo(context.Context, *Request, *Response) error
}

func RegisterSSHHandler(s server.Server, hdlr SSHHandler, opts ...server.HandlerOption) error {
	type sSH interface {
		Echo(ctx context.Context, in *Request, out *Response) error
	}
	type SSH struct {
		sSH
	}
	h := &sSHHandler{hdlr}
	return s.Handle(s.NewHandler(&SSH{h}, opts...))
}

type sSHHandler struct {
	SSHHandler
}

func (h *sSHHandler) Echo(ctx context.Context, in *Request, out *Response) error {
	return h.SSHHandler.Echo(ctx, in, out)
}
