// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.0--rc1
// source: models.proto

package models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SSHClient is the client API for SSH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSHClient interface {
	Echo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sSHClient struct {
	cc grpc.ClientConnInterface
}

func NewSSHClient(cc grpc.ClientConnInterface) SSHClient {
	return &sSHClient{cc}
}

func (c *sSHClient) Echo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/models.SSH/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SSHServer is the server API for SSH service.
// All implementations must embed UnimplementedSSHServer
// for forward compatibility
type SSHServer interface {
	Echo(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSSHServer()
}

// UnimplementedSSHServer must be embedded to have forward compatible implementations.
type UnimplementedSSHServer struct {
}

func (UnimplementedSSHServer) Echo(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedSSHServer) mustEmbedUnimplementedSSHServer() {}

// UnsafeSSHServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSHServer will
// result in compilation errors.
type UnsafeSSHServer interface {
	mustEmbedUnimplementedSSHServer()
}

func RegisterSSHServer(s grpc.ServiceRegistrar, srv SSHServer) {
	s.RegisterService(&SSH_ServiceDesc, srv)
}

func _SSH_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSHServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.SSH/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSHServer).Echo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SSH_ServiceDesc is the grpc.ServiceDesc for SSH service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SSH_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "models.SSH",
	HandlerType: (*SSHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _SSH_Echo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models.proto",
}
